

INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("send.1633867@gmail.com","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("itai.bolyasni@gmail.com","Hello","test","test", 2, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("dr.who@gmail.com","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("AOT@hotmail.com","Hello","test","test", 2, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("receive@gmail.com","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("test@gmail.com","Hello","test","test", 2, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("blah@gmail.com","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("somemoreEntries@gmail.com","Hello","test","test", 2, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("uhhh@gmail.com","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("tooManyThings@gmail.com","Hello","test","test", 2, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("cool_kid_90@gmail.com","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("kid_above_isnt_cool@gmail.com","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("lol@gmail.com","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("wut@gmail.com","Hello","test","test", 2, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("wat@gmail.com","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("wet.1633867@gmail.com","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("woot.1633867@gmail.com","Hello","test","test", 2, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("moreTEst","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("loremipsum@gmail.com","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("tooManyThings@gmail.com@gmail.com","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("send.1633867@gmail.com","Hello","test","test", 2, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("send.1633867@gmail.com","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("tooManyThings@gmail.com@gmail.com","Hello","test","test", 2, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("send.1633867@gmail.com","Hello","test","test", 1, CURRENT_DATE);
INSERT INTO Emails(senderEmail, subject, textMsg, htmlMsg, folder_id, sentDate) VALUES ("kid_above_isnt_cool@gmail.com","Something Different","test","test", 1, CURRENT_DATE);

INSERT INTO RecipientAddress(emailAddress) VALUES ("receive.1633867@gmail.com");
INSERT INTO RecipientAddress(emailAddress) VALUES ("send.1633867@gmail.com");
INSERT INTO RecipientAddress(emailAddress) VALUES ("blah.1633867@gmail.com");
INSERT INTO RecipientAddress(emailAddress) VALUES ("wut.1633867@gmail.com");
INSERT INTO RecipientAddress(emailAddress) VALUES ("hahaGG.1633867@gmail.com");


INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",1,1);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",2,2);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",3,1);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("BCC",4,1);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",5,3);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("CC",6,1);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",7,2);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",8,4);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("CC",9,1);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("BCC",10,2);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",11,2);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",12,2);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",13,1);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",14,3);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",15,5);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",16,4);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",17,1);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",18,2);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",19,5);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",20,4);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",21,3);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",22,4);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",23,5);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",24,2);
INSERT INTO Recipient(type,email_id, address_id) VALUES ("TO",25,1);
